# fly.toml app configuration file generated for dark-forest-3926 on 2023-09-18T23:05:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-forest-3926"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
